Added login page
nethesis/nethvoice-cti pull request #11
Opened 2022-10-18 15:15 UTC by tonyco97

2022-10-18 15:30 UTC, SebastianMB-IT requested changes
Resolve the comments in the code and remember to add alerts in case of wrong password or other errors.

2022-10-18 15:30 UTC, SebastianMB-IT commented on pages/login.tsx
> +import { TextInput } from '../components/common'
This import with the one below can be merged.

2022-10-18 15:30 UTC, SebastianMB-IT commented on pages/login.tsx
> +import { MdLock } from 'react-icons/md'
The same thing as the comment above.

2022-10-18 15:30 UTC, SebastianMB-IT commented on pages/login.tsx
> +    const username = (target.querySelector('input[name="username"]') as HTMLInputElement).value
Could you use refs in React instead querySelectors?

2022-10-19 15:28 UTC, SebastianMB-IT requested changes

2022-10-19 15:28 UTC, SebastianMB-IT commented on pages/login.tsx
> +      router.push('/')
The token must be saved inside the browser!

2022-10-20 10:42 UTC, SebastianMB-IT requested changes

2022-10-20 10:42 UTC, SebastianMB-IT commented on pages/login.tsx
> +  function checkToken() {
Put this function inside the lib directory.

2022-10-20 10:42 UTC, SebastianMB-IT commented on pages/login.tsx
> +  function setToken(token: any) {
Do the same as above.

2022-10-21 12:50 UTC, SebastianMB-IT approved these changes

2022-10-21 14:50 UTC, andre8244 approved these changes

2022-10-21 14:53 UTC, merged