Changed loader and alert inside login
nethesis/nethvoice-cti pull request #15
Opened 2022-10-24 12:04 UTC by tonyco97

2022-10-25 15:39 UTC, SebastianMB-IT requested changes

2022-10-25 15:39 UTC, SebastianMB-IT commented on components/common/Alert.tsx
> +  informationType?: 'info' | 'warning' | 'success' | 'error'
It's better to name this prop _type_.

2022-10-25 15:39 UTC, SebastianMB-IT commented on pages/login.tsx
> +            setMessaggeError('the network connection is lost')
This probably must be capitalized.

2022-10-26 09:11 UTC, SebastianMB-IT approved these changes

2022-10-26 09:34 UTC, andre8244 approved these changes

2022-10-26 10:12 UTC, merged